tags:
- name:
  description: API

paths:
  /product:
    post:
      tags:
      - Product
      summary: Add Product
      parameters:
      - name: body
        in: body
        description: Product Data
        required: true
        schema:
          $ref: '#/definitions/product'
      responses:
        201:
          description: 'Created'
        409:
          description: 'Bad Request'
        500:
          description: 'Server Error'
  /product/search:
    post:
      tags:
      - Product
      summary: Search Product
      parameters:
      - name: body
        in: body
        description: Product search fields
        required: false
        schema:
          $ref: '#/definitions/searchProduct'
      responses:
        200:
          description: 'OK'
        204:
          description: 'No Content'
        500:
          description: 'Server Error'
  /checkout:
    post:
      tags:
      - Cart
      summary: Add to Cart
      parameters:
      - name: body
        in: body
        description: Cart Data
        required: true
        schema:
          $ref: '#/definitions/checkout'
      responses:
        200:
          description: 'Created'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'
  /checkout/addToCart:
    post:
      tags:
      - Cart
      summary: Add to Cart
      parameters:
      - name: body
        in: body
        description: Cart Data
        required: true
        schema:
          $ref: '#/definitions/addToCart'
      responses:
        200:
          description: 'Success'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'

definitions:
  checkout:
    type: object
    properties:
      cartId:
        type: number
        description: cartId
      userId:
        type: number
        description: userId
  addToCart:
    type: object
    properties:
      userId:
        type: number
        description: title
      cartItems:
        type: array
        description: cartItems
        items:
          $ref: '#/definitions/cartItems'
  cartItems:
    type: object
    properties:
      productId:
        type: number
        description: productId
      quantity:
        type: number
        description: quantity
  searchProduct:
    type: object
    properties:
      title:
        type: string
        description: title
      description:
        type: string
        description: Description
      sortField:
        type: string
        description: sortField
      sortDirection:
        type: string
        description: sortDirection
  product:
    type: object
    required:
        - title
        - description
        - pictureUrl
        - price
        - quantity
    properties:
      title:
        type: string
        description: title
      description:
        type: string
        description: Description
      pictureUrl:
        type: string
        description: pictureUrl
      price:
        type: number
        description: price
      quantity:
        type: number
        description: quantity
schemes:
 - https
 - http
